### ISSUE TITLE
MicrobiologyTest radio breaks Investigation modal

### ISSUE THREAD

**Issue by Iain-S** [openhealthcare/opal#1678]
Hi

When installing Opal from scratch, the Patient Details -> Investigations modal will not show and an error can be seen in the logs.  This seems to be because the MicrobiologyTest model was deleted some time ago but there is still a radio button in investigation_form.html that refers to it.

I have tried this with both the PyPI Opal and by installing from github source code branch v0.12.1

## Steps to reproduce

1. Install Opal as-per the instructions [here](https://opal.openhealthcare.org.uk/docs/installation/)
2. Follow the [tutorial](https://opal.openhealthcare.org.uk/docs/tutorial/#test-it-out) as far as "Test it out"
3. Start the server and navigate to Team Lists
4. Add a patient and click Patient Details in the left-hand column
5. Click the Investigations + button
6. The modal does not appear and an exception is raised (see below)

## Potential fix
Comment-out or remove this line from opal/templates/forms/investigation_form.html
`{% radio field="MicrobiologyTest.rhinovirus" %}`

## Traceback
[05/Feb/2019 13:48:15] "GET /templates/modals/treatment.html/ HTTP/1.1" 200 6595
Internal Server Error: /templates/modals/investigation.html/
Traceback (most recent call last):
  File "/home/.../python3.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  .....
  File "/home/.../opal-0.12.1/opal/templatetags/forms.py", line 236, in radio
    return _radio(*args, **kwargs)
  File "/home/.../opal-0.12.1/opal/templatetags/forms.py", line 229, in _radio
    ctx = extract_common_args(kwargs)
  File "/home/.../opal-0.12.1/opal/templatetags/forms.py", line 116, in extract_common_args
    args = infer_from_subrecord_field_path(kwargs["field"])
  File "/home/.../opal-0.12.1/opal/templatetags/forms.py", line 71, in infer_from_subrecord_field_path
    model, field = _model_and_field_from_path(subRecordFieldPath)
  File "/home/.../opal-0.12.1/opal/templatetags/forms.py", line 55, in _model_and_field_from_path
    model = get_subrecord_from_model_name(model_name)
  File "/home/.../opal-0.12.1/opal/core/subrecords.py", line 59, in get_subrecord_from_model_name
    raise ValueError("unable to find a model for {}".format(model_name))
ValueError: unable to find a model for MicrobiologyTest
[05/Feb/2019 13:48:20] "GET /templates/modals/investigation.html/ HTTP/1.1" 500 232049

I believe this may be related to this commit: https://github.com/openhealthcare/elcid-rfh/tree/315-remove-models-lo-longer-used

**Comment by fredkingham** [comment]
Hi Iain, 
You are quite right! We released opal v0.12.1 last night to fix this.

Sorry about that.

It should be noted that out of the box the investigations field is little more than a mapping of free text test name to free text result details with a date field.

This default behaviour can be enhanced by adding these https://gist.github.com/fredkingham/684d6885a87993475d20b87fce899bd2 to your lookuplists.json

However at present we are looking to remodel this logic as we find it fiddly and unintuitive. There's a good chance a test_name > details is actually what you want.

Thanks for raising the issue!
