### ISSUE TITLE
Error on running tests

### ISSUE THREAD

**Issue by JMathiszig-Lee** [openhealthcare/opal#1874]
Followed the instructions in the documentation to build a test environment however tests do not build because a package references six which was removed from django 3 i think

Running Python Unit Tests
Traceback (most recent call last):
  File "runtests.py", line 132, in <module>
    django.setup()
  File "/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django_reversion-3.0.1-py3.8.egg/reversion/__init__.py", line 21, in <module>
    from reversion.revisions import (  # noqa
  File "/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django_reversion-3.0.1-py3.8.egg/reversion/revisions.py", line 13, in <module>
    from django.utils import timezone, six
ImportError: cannot import name 'six' from 'django.utils' (/root/.local/share/virtualenvs/opal-WeZMokl1/lib/python3.8/site-packages/django/utils/__init__.py)

**Comment by davidmiller** [comment]
Interesting. I just built a new environment and didn't get this error.
Can you post the output of pip freeze ?

**Comment by JMathiszig-Lee** [comment]
amqp==1.4.9
anyjson==0.3.3
asgiref==3.2.10
billiard==3.3.0.23
celery==3.1.25
certifi==2020.6.20
chardet==3.0.4
coverage==5.1
coveralls==2.0.0
Django==3.0.7
django-appconf==1.0.4
django-axes==1.7.0
django-celery==3.2.2
django-compressor==2.2
django-reversion==3.0.1
djangorestframework==3.10.2
docopt==0.6.2
entrypoints==0.3
ffs==0.0.8.2
flake8==3.7.8
idna==2.8
Jinja2==2.10.1
kombu==3.0.37
letter==0.5
MarkupSafe==1.1.1
mccabe==0.6.1
-e git+git@github.com:JMathiszig-Lee/opal.git@9c6f2c917e562a8fc33124ac6bf513dce9c116a4#egg=opal
psycopg2==2.8.3
pycodestyle==2.5.0
pyflakes==2.1.1
python-dateutil==2.8.0
pytz==2020.1
rcssmin==1.0.6
requests==2.22.0
rjsmin==1.0.12
six==1.15.0
sqlparse==0.3.1
urllib3==1.25.9

**Comment by davidmiller** [comment]
Right - you're running on a forked branch that includes a pipfile.lock that specifies Django 3+ rather than the 2.0.13 specified by opal/setup.py without also upgrading the related dependancies... 

This is a novel interpretation of `Followed the instructions in the documentation` 😁  

This commit:  https://github.com/openhealthcare/opal/commit/9c6f2c917e562a8fc33124ac6bf513dce9c116a4 

The changes to opal/core/referencedata/data/lookuplists/symptom.json  - grand. 
The three other new files, less so - I think you'll want to do some version of git reset HEAD^1 add opal/core/referencedata/data/lookuplists/symptom.json  commit -m "Your message" to remove the 3 files, and you'll need to reset your env if you've wound up with Django 3.

**Comment by JMathiszig-Lee** [comment]
🤦‍♂️ my bad. 

I thought i'd run setup.py first but clearly had the the order wrong hence the introduction of the wrong django! Those files will be gone on the next push. I'm working on adding codes to some of the other reference data too

**Comment by JMathiszig-Lee** [comment]
Tests now running after idiocy corrected
