### ISSUE TITLE
Trying to start project from opal source code

### ISSUE THREAD

**Issue by afoone** [openhealthcare/opal#423]
I've cloned the project in my workspace and executed

`python setup.py install`

Everything seemed to be ok. But I've executed then:

`opal startproject pruebas`

And I get this error:

```
Creating project dir at /Users/afoone/Documents/workspace-python/pruebas
Bootstrapping your OPAL project...
Traceback (most recent call last):
  File "/usr/local/bin/opal", line 4, in <module>
    __import__('pkg_resources').run_script('opal==0.5.3', 'opal')
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 724, in run_script
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 1657, in run_script
  File "/Library/Python/2.7/site-packages/opal-0.5.3-py2.7.egg/EGG-INFO/scripts/opal", line 404, in <module>
    
  File "/Library/Python/2.7/site-packages/opal-0.5.3-py2.7.egg/EGG-INFO/scripts/opal", line 399, in main
    
  File "/Library/Python/2.7/site-packages/opal-0.5.3-py2.7.egg/EGG-INFO/scripts/opal", line 99, in startproject
    
  File "/Library/Python/2.7/site-packages/ffs-0.0.8.1-py2.7.egg/ffs/path.py", line 419, in ls
    raise exceptions.DoesNotExistError(msg)
ffs.exceptions.DoesNotExistError: Cannot access /Library/Python/2.7/site-packages/opal-0.5.3-py2.7.egg/EGG-INFO/scripts/scaffold: No such file or directory
```
Before that, trying to run opal by the installation tutorial doesn't work:

```
sudo -H pip install opal
Collecting opal
  Downloading opal-0.5.3.post.tar.gz (9.2MB)
    100% |████████████████████████████████| 9.2MB 39kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-w4BOHd/opal/setup.py", line 5, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
    IOError: [Errno 2] No such file or directory: '/private/tmp/pip-build-w4BOHd/opal/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-w4BOHd/opal
```

Tnx

**Comment by davidmiller** [comment]
Hi @afoone - something's clearly going wrong with our setup.py not including the right things - let me look into it and get back to you...

**Comment by davidmiller** [comment]
Hi @afoone 

This should now be fixed - either from source via setup.py install or pip installing the new package I just pushed.

Please do let us know if you have any questions or find any more issues!

**Comment by afoone** [comment]
It is working perfect. ¡Many thanks!
