### ISSUE TITLE
Icons - Maybe I Know What I'm Doing, Maybe I Don't, Shut Up, And Let Me Do It Anyway.

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#482]
Passing an icon string that doesn't start with glyphicon or fa raises an error in `{% icon %}`.
Let's not do that - because errors in templatetags are irritating.

```
Traceback (most recent call last):
  File "/usr/lib/ohc/elcid-rfh/elcid/test/test_views.py", line 100, in test_episode_list_template_view
    self.assertStatusCode('/templates/episode_list.html/', 200)
  File "/usr/lib/ohc/opal/opal/core/test.py", line 50, in assertStatusCode
    response = self.client.get(path)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/vagrant/.virtualenvs/elcid-rfh/local/lib/python2.7/site-packages/django/template/base.py", line 1271, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/usr/lib/ohc/opal/opal/templatetags/forms.py", line 210, in icon
    return dict(icon=icon)
UnboundLocalError: local variable 'icon' referenced before assignment
```

**Comment by davidmiller** [comment]
Closed by #483
